extract:
  raw_data_file_path: "data/raw"
  raw_data_body_file_path: "data/raw/body"
  raw_data_metadata_file_path: "data/raw/metadata"
  from_date: "2010-01-01"
  to_date: "2010-01-01"
  order_by: "newest"
  show_fields: "all"
  page_size: 200
  endpoint: "https://content.guardianapis.com/search"